import { test, expect } from '@playwright/test';
test('demo CRUD persists, handles empty state, and fits desktop/mobile', async ({page},testInfo)=>{
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'每一份订阅，都有数。'})).toBeVisible();
  await expect(page.getByRole('button',{name:/ChatGPT Plus/})).toBeVisible();
  await page.getByRole('button',{name:'添加订阅',exact:true}).click();
  await page.getByLabel('服务名称',{exact:true}).fill('Test Service');
  await page.getByLabel('当前方案').fill('Personal');
  await page.getByLabel('每期金额').fill('12.50');
  await page.getByLabel('取消订阅的方式').fill('账户设置 → 取消');
  await page.getByRole('button',{name:'保存订阅'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await page.getByRole('button',{name:'Test Service Personal'}).click();
  await page.getByRole('button',{name:'编辑订阅',exact:true}).click();
  await page.getByLabel('每期金额').fill('18');
  await page.getByRole('button',{name:'保存订阅'}).click();
  await page.getByRole('button',{name:'Test Service Personal'}).click();
  await expect(page.getByText('¥18.00 · 每月')).toBeVisible();
  await page.getByRole('button',{name:'删除记录',exact:true}).click();
  await expect(page.getByRole('heading',{name:'删除这条订阅记录？'})).toBeVisible();
  await page.getByRole('button',{name:'删除记录',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('textbox',{name:'搜索订阅'}).fill('no-match-123');
  await expect(page.getByRole('heading',{name:'没有匹配的订阅'})).toBeVisible();
  await page.getByRole('textbox',{name:'搜索订阅'}).fill('');
  const overflow = await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth); expect(overflow).toBe(false);
  const toastClose = page.getByRole('button',{name:'关闭提示'}); if(await toastClose.isVisible()) await toastClose.click();
  await page.getByRole('heading',{name:'每一份订阅，都有数。'}).click();
  await page.screenshot({path:`test-results/renewal-${testInfo.project.name}.png`,fullPage:true});
  if(testInfo.project.name==='mobile')await page.getByRole('button',{name:'打开菜单'}).click();
  await page.getByRole('button',{name:'设置与数据',exact:true}).click();
  const download=page.waitForEvent('download'); await page.getByRole('button',{name:'导出 CSV'}).click(); expect((await download).suggestedFilename()).toMatch(/\.csv$/);
  await expect(page.getByRole('heading',{name:'GitHub 同步'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'最近的提醒记录'})).toHaveCount(0);
});
test('import confirmation, archive filter, cancellation URL and PWA metadata',async({page})=>{
  await page.goto('/');
  const nextDate=new Date(Date.now()+4*86400000).toISOString();
  const record={service_name:'Imported Service',plan:'Annual',price:100,currency:'EUR',billing_cycle:'yearly',next_billing_at:nextDate,timezone:'Asia/Shanghai',billing_anchor_day:1,cancellation_method:'Account → Cancel',cancellation_url:'https://example.com/cancel',notes:'Imported notes',auto_renew:false,reminder_enabled:false,active:false};
  await page.locator('input[type=file]').setInputFiles({name:'import.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,subscriptions:[record]}))});
  await expect(page.getByRole('heading',{name:'导入 1 条订阅？'})).toBeVisible();
  await page.getByRole('button',{name:'确认导入'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Imported Service Annual'})).toHaveCount(0);
  await page.getByRole('button',{name:'已停用',exact:true}).click();
  await page.getByRole('button',{name:'Imported Service Annual'}).click();
  await expect(page.getByRole('link',{name:'打开取消页面'})).toHaveAttribute('href','https://example.com/cancel');
  await expect(page.getByText('Imported notes')).toBeVisible();
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  const manifest=await(await page.request.get('/manifest.webmanifest')).json();expect(manifest.display).toBe('standalone');expect(manifest.icons).toHaveLength(2);
  await expect.poll(()=>page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();return !!r?.active;})).toBe(true);
});
